In [1]:
from PIL import Image

s=input()
paper=Image.open('Dataset_handwritten/paper.jpeg')
#rint(paper.width,paper.height)
width=paper.width-50
fw=0
fh=0
for i in s:
    if i==' ':
        #img=Image.open('handwriting/n.jpeg')
        fw=fw+30
    else:
        if i.isupper():
            img=Image.open('Dataset_handwritten/{}.jpeg'.format(i))
            #w=img.width+fw
            if width<fw:
                fw=0
                fh=fh+100
                paper.paste(img,(fw,fh))
            else:
                paper.paste(img, (fw,fh))
            fw=img.width+fw
        elif i.islower():
            img=Image.open('Dataset_handwritten/{}1.jpeg'.format(i.upper()))
            #w=img.width+fw
            if width<fw:
                fw=0
                fh=fh+100
                paper.paste(img,(fw,fh))
            else:
                paper.paste(img, (fw,fh))
            fw=img.width+fw
        elif i.isdigit():
            img=Image.open('Dataset_handwritten/{}.jpeg'.format(i))
            #w=img.width+fw
            if width<fw:
                fw=0
                fh=fh+100
                paper.paste(img,(fw,fh))
            else:
                paper.paste(img, (fw,fh))
            fw=img.width+fw
        else:
            img=Image.open('Dataset_handwritten/{}.jpeg'.format(i))
            #w=img.width+fw
            if width<fw:
                fw=0
                fh=fh+100
                paper.paste(img,(fw,fh))
            else:
                paper.paste(img, (fw,fh))
            fw=img.width+fw
            
paper.show()

hello world


In [141]:
#modifying images code

import cv2 
import numpy as np 
from PIL import Image
im=cv2.imread('Orginal_handwritten/N1.jpg') 
img=np.copy(im)
greyimg=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
print(np.asarray(greyimg))
cv2.imshow('image',greyimg)
cv2.waitKey(0)
for i in range(len(greyimg)):
    for j in range(len(greyimg[i])):
        #greyimg[i][j]=240
        if greyimg[i][j]<180:
            greyimg[i][j]=40
        else:
            greyimg[i][j]=240
print("\n\n\n\n")
print(np.asarray(greyimg))
cv2.imshow('image',greyimg)
cv2.imwrite('Dataset_handwritten/N1.jpeg',greyimg)
cv2.waitKey(0)


[[237 238 235 ... 237 238 238]
 [231 232 233 ... 239 240 242]
 [231 231 231 ... 241 242 242]
 ...
 [246 254 255 ... 222 246 247]
 [251 251 253 ... 244 248 247]
 [252 240 240 ... 250 246 249]]





[[240 240 240 ... 240 240 240]
 [240 240 240 ... 240 240 240]
 [240 240 240 ... 240 240 240]
 ...
 [240 240 240 ... 240 240 240]
 [240 240 240 ... 240 240 240]
 [240 240 240 ... 240 240 240]]


-1